// This file is generated by Prismic local builder. Update with care!

export { default as FooterColumn } from './FooterColumn'
export { default as MenuSimple } from './MenuSimple'
export { default as MenuWithIcons } from './MenuWithIcons'
export { default as MenuWithoutIcon } from './MenuWithoutIcon'
export { default as SubCategory } from './SubCategory'
